# Generated by Django 6.0.2 on 2026-03-04 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone must be in format: '+234XXXXXXXXXX'", regex='^\\+234\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone must be in format: '+234XXXXXXXXXX'", regex='^\\+234\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='cv_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='live_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone must be in format: '+234XXXXXXXXXX'", regex='^\\+234\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone must be in format: '+234XXXXXXXXXX'", regex='^\\+234\\d{10}$')]),
        ),
    ]
