# Generated by Django 6.0 on 2026-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_companyprofile_proposed_meeting_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('phone', 'Phone Verification'), ('company_access', 'Company Access'), ('profile_access', 'Profile Access'), ('company_email', 'Company Email')], max_length=20),
        ),
    ]
