# Generated by Django 6.0.2 on 2026-03-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_user_phone_number_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='id_card_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
