# Generated by Django 6.0.2 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_alter_freelancerprofile_id_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('phone', 'Phone Verification'), ('company_email', 'Company Email')], max_length=20),
        ),
    ]
