# Generated by Django 6.0.2 on 2026-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_alter_otpverification_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
