# Generated by Django 6.0.2 on 2026-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_companyprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='proposed_meeting_dates',
            field=models.JSONField(blank=True, default=list, help_text='Up to 3 proposed meeting datetimes submitted by the company'),
        ),
    ]
