from .auth import AuthViewSet
from .otp import OTPViewSet
from .freelancer_profile import FreelancerProfileViewSet
from .company_profile import CompanyProfileViewSet
from .job_posting import JobPostingViewSet
from .job_application import JobApplicationViewSet
from .contract import ContractViewSet
from .payment import PaymentViewSet
from .workspace import WorkspaceViewSet
from .task import TaskViewSet
from .message import MessageViewSet
from .admin import AdminViewSet